from passrotate.providers.amazon import Amazon
from passrotate.providers.cloudflare import Cloudflare
from passrotate.providers.digitalocean import DigitalOcean
from passrotate.providers.discord import Discord
from passrotate.providers.github import GitHub
from passrotate.providers.linode import Linode
from passrotate.providers.namecheap import Namecheap
from passrotate.providers.pixiv import Pixiv
from passrotate.providers.twitter import Twitter
from passrotate.providers.ycombinator import YCombinator
from passrotate.providers.facebook import Facebook
from passrotate.providers.zotero import Zotero
from passrotate.providers.pypi import PyPI
from passrotate.providers.ankiweb import AnkiWeb
from passrotate.providers.gitlab import GitLab
from passrotate.providers.wikipedia import Wikipedia
from passrotate.providers.aur import ArchUserRepository
from passrotate.providers.mastodon import Mastodon
